Work around a Firefox 4 iframe bug that causes __GetTokenPage_gotToken to be called twice.
Before this fix, about half the time we saw something like this:

Error: Test ended with 1 uncleared timeouts/intervals:

setTimeout_pending #86, created at:
> anonymous((function () {iframeD.callback(null);}),0) at https://c1.linuxwan.com:444/js_coreweb/cw/unittest.js:1649
> anonymous(&quot;AACjQUwCq8VQcgC_cTRm2dL0&quot;) at https://c1.linuxwan.com:444/js_minerva/cw/net/TestClient.js:483